version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.1
     steps:
       - checkout
       - run: echo "hello world"
   test:
      override:
         - py.test ./tests
   
   dependencies:
      pre:
         -  pip install pytest
